### ISSUE TITLE
ejemplo más liviano

### ISSUE THREAD

**Issue by mauriciopasquier** [lainventoria/stl2gif-ruby#1]
@sudoaza podés conseguirte un stl que pese menos? (mucho menos)

me viene bien para el wrapper de authentise también.

**Comment by sudoaza** [comment]
hecho c6d81c5fc9

**Comment by mauriciopasquier** [comment]
On Thu, Dec 04, 2014 at 01:55:35PM -0800, aza wrote:

> Closed #1.

me parece sospechoso algo 3D con dos caras pero bueno..

##

**Comment by sudoaza** [comment]
de hecho es 1 sola cara pero como es un cuadrado son 2 triangulos :P

2014-12-04 19:54 GMT-03:00 Mauricio Pasquier Juan notifications@github.com
:

**Comment by mauriciopasquier** [comment]
On Thu, Dec 04, 2014 at 06:59:33PM -0800, aza wrote:

> de hecho es 1 sola cara pero como es un cuadrado son 2 triangulos :P

y cómo se imprime? digo, no tiene que tener espesor o algo así (en forma de más
caras)?

##

**Comment by sudoaza** [comment]
mmmm eso me preguntaba el otro dia, no se como transformara de caras 2D a
recorrido, pero calculo lo tendran solucionado, no hay una forma de
representar solido y no solido en stl
